# 任务列表，一个任务会启用一个单独的协程进行跟踪:
[[task]]
source = [ "/root/..."]
target = "user@dns.com:/backData/host/dns/root/"
# 若使用ssh传送文件到远程服务器，需要使用sshpass程序和密码文件来自动填充密码
#具体使用细节请参考sshpass相关文档
#rsync 支持单括号引用参数.
para = '--exclude=".*" --exclude="*.swp" --exclude="*.swap" -rt -e "sshpass -f ./pass-file ssh -p 7788"'  

[[task]]
isTemp = false  #如果 isTemp 是 true，则忽略该任务，给大家用来注释标注还没有完成配置的任务。
source = [ "/data/t4", "/data/t5/" ]
target = "/root/temp/"
para = '-atogp '

[[task]]
isTemp = true  #如果不给出本项，本项默认就是false,如果是true这项不执行监测和同步。
source = [ "/data/t4", "/data/t5/" ]
target = "user@dns.com:~/rdata/"
para = "-rt -e 'sshpass -f ./pass-file ssh -p 7788'"  #rsync 支持单括号引用参数.
